# Generated by Django 3.0.4 on 2020-03-19 00:35

import clinic.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('twilio_jwt', models.TextField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=70)),
                ('credentials', models.FileField(upload_to=clinic.models.upload_filename)),
                ('verified', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ietf_tag', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SelfCertificationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('twilio_jwt', models.TextField(blank=True, editable=False, null=True)),
                ('session_started', models.DateTimeField(blank=True, null=True)),
                ('session_ended', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.Doctor')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.ManyToManyField(to='clinic.Language'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='self_certification_questions',
            field=models.ManyToManyField(to='clinic.SelfCertificationQuestion'),
        ),
    ]
