# Generated by Django 3.0.4 on 2020-03-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfcertificationquestion',
            name='sort_order',
            field=models.PositiveIntegerField(),
        ),
    ]
