# Generated by Django 3.0.4 on 2020-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfCertificationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='self_certification_questions',
            field=models.ManyToManyField(to='clinic.SelfCertificationQuestion'),
        ),
    ]
