# Generated by Django 3.0.4 on 2020-03-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='enable_video',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='ietf_tag',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='selfcertificationquestion',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
