# Generated by Django 3.0.4 on 2020-03-18 18:44

from django.db import migrations, models
import django.db.models.deletion
import sort_order_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20200318_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='online',
        ),
        migrations.AddField(
            model_name='doctor',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='selfcertificationquestion',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
