# Generated by Django 3.0.4 on 2020-03-18 22:03

import clinic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_auto_20200318_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='selfcertificationquestion',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='doctor',
            name='twilio_jwt',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='twilio_jwt',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='credentials',
            field=models.FileField(upload_to=clinic.models.upload_filename),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinic.Doctor'),
        ),
    ]
